### ISSUE TITLE
Should the parameter collapsing be optional or even off by default?

### ISSUE THREAD

**Issue by jeffbski** [williamkapke/sqlbits#2]
I am having some second thoughts about the auto parameter collapsing. 

A while back we made the change to not collapse null params and that avoided many problematic situations, but recently I hit another one.

My recent issue occurred when I had an integer column and string column and the values were coming in from a browser POST as strings (from text box), and if I had say '500' for the two of them they were collapsed down to the same param, but this fails when inserting or updating since they are different column types. To work around, I had to force one to an integer so that it wasn't the same value.

So I am wondering whether param collapsing should be optional and maybe even the default should be off for safety. Most of the other tools I have used in the past (on Java and such) did not collapse params, so I am wondering if maybe that is the less problematic approach. The main issue is that we don't know the column types up front, so that's why collapsing can be an issue (at least with postgres). I'm sure there may be other similar cases like booleans or anything that coerce.

When I have a chance, I can put together a test and all, most of this is just from memory.

I love using SQLBits though, thanks!

**Comment by jeffbski** [comment]
@williamkapke I was wondering if you had thought any more about this. Basically, I would like a way to change the config of sqlbits specifically to disable the auto parameter collapsing. We could do this globally or have a function to create a new instance.

The main issue is that the auto parameter collapsing causes issues when the parameters are being used for different data types in columns. For instance let's say you have Columns: [ statusCode, statusMsg, id]

The params coming in might be { statusCode: '500', statusMsg: '500', id: '500' }, so sqlbits will automatically think it can use the same param for all. However if these are different data types in the columns string, number, bigint, text, blob, json, ... then Postgres will not be happy and fails with an exception. 

So I want to be able to disable the auto parameter collapsing, unless you are ok with turning it off altogether (which is the only safe thing to do in my opinion). 

If you are ok with turning it off altogether, then we can do that and I don't need configuration options.

Otherwise if you still want to have that feature, then I need a way to be able to disable it otherwise queries can just start breaking when data accidentally starts matching up.

Let me know what you think.

**Comment by williamkapke** [comment]
Yeah- I think it should probably be NON-collapsing by default. How about this:
```javascript
//default NON-collapsing behavior
var bits = require("./bits");
var sql = bits.SELECT("*").WHERE({a:1,b:2,c:1})
console.log(sql.sql); //SELECT * WHERE(a=$1 AND b=$2 AND c=$3)
console.log(sql.params); //[ 1, 2, 1 ]
```
```javascript
//make collapsing per context
var bits = require("./bits");
var sql = bits.SELECT("*").WHERE({a:1,b:2,c:1})
sql.collapse = true;
console.log(sql.sql); //SELECT * WHERE(a=$1 AND b=$2 AND c=$1)
console.log("params: ", sql.params); //[ 1, 2 ]
```
```javascript
//make it globally collapsing
var bits = require("./bits");
bits.Context.collapse = true;
var sql = bits.SELECT("*").WHERE({a:1,b:2,c:1})
console.log(sql.sql); //SELECT * WHERE(a=$1 AND b=$2 AND c=$1)
console.log("params: ", sql.params); //[ 1, 2 ]
```

Browse commit b01bc95223727d2bc19644ecfe7e622231296b78 on the `no-collapse` branch and LMK what you think. (some formatting got messed up in that commit- I'll fix it later)

**Comment by jeffbski** [comment]
Looks great! I like that.

**Comment by jeffbski** [comment]
Thanks for the fix. I can get rid of my hacked branch after that is in :-)

**Comment by williamkapke** [comment]
pushed and published- enjoy!

**Comment by jeffbski** [comment]
Awesome! Have a great rest of your weekend!
